### ISSUE TITLE
Toast.js doesn't work on Meteor 0.6.0

### ISSUE THREAD

**Issue by awesomepan** [srackham/toast.js#1]
Toast.js doesn't work on Meteor 0.6.0, because of  

We've added file-level JavaScript variable scoping. Variables declared with var at the outermost level of a JavaScript source file are now private to that file. Remove the var to share a value between files.

ReferenceError: Toast is not defined
[Break On This Error]  
Toast.info(message);

Please help to update it, thank you for coding :)

**Comment by srackham** [comment]
I think this 0.6.0 scoping feature is unfortunate. I'll look at updating when the dust has settled (https://groups.google.com/forum/?fromgroups=#!topic/meteor-talk/gYgYhv88nB4). In the mean time pin your app to Meteor 0.5.9

**Comment by awesomepan** [comment]
@srackham thanks :)

**Comment by srackham** [comment]
Fixed in toastjs v2.0.5
